// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Quartz.DataAccess.Concrete.EntityFramworkCore.Context;

namespace Quartz.DataAccess.Migrations
{
    [DbContext(typeof(QuartzContext))]
    [Migration("20221206083800_vw_SearchItem_added")]
    partial class vw_SearchItem_added
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Quartz.Entities.Concrete.FileUploads.FileUpload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Extension")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FileUploads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 11, 24, 11, 40, 23, 645, DateTimeKind.Local).AddTicks(4467),
                            Extension = ".jpg",
                            Name = "MainDrawing",
                            Path = "wwwroot\\Files\\MainDrawing.jpg",
                            Type = "image/jpeg",
                            UploadedBy = "QUARTZ"
                        });
                });

            modelBuilder.Entity("Quartz.Entities.Concrete.LookUpItems.LookUpItemsComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LookupItemsComponentTypes");
                });

            modelBuilder.Entity("Quartz.Entities.Concrete.LookUpItems.LookUpItemsFittingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LookupItemsFittingTypes");
                });

            modelBuilder.Entity("Quartz.Entities.Concrete.LookUpItems.LookUpItemsMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LookupItemsMethods");
                });

            modelBuilder.Entity("Quartz.Entities.Concrete.LookUpItems.LookUpItemsOperator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LookupItemsOperators");
                });

            modelBuilder.Entity("Quartz.Entities.Concrete.LookUpItems.LookUpItemsPlantArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LookupItemsPlantAreas");
                });

            modelBuilder.Entity("Quartz.Entities.Concrete.LookUpItems.LookUpItemsPlantSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("LookUpItemsPlantAreas")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LookupItemsPlantSystems");
                });

            modelBuilder.Entity("Quartz.Entities.Concrete.LookUpItems.LookUpItemsProcedure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("LookUpItemsMethod")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LookupItemsProcedures");
                });

            modelBuilder.Entity("Quartz.Entities.Concrete.LookUpItems.LookUpItemsSpecification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LookupItemsSpecifications");
                });

            modelBuilder.Entity("Quartz.Entities.Concrete.LookUpItems.LookUpItemsStandardStatement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LookupItemsStandardStatements");
                });

            modelBuilder.Entity("Quartz.Entities.Concrete.LookUpItems.LookUpItemsStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LookupItemsStatuses");
                });

            modelBuilder.Entity("Quartz.Entities.Concrete.LookUpItems.LookUpItemsTechnique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("LookUpItemsProcedure")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LookupItemsTechniques");
                });

            modelBuilder.Entity("Quartz.Entities.Concrete.LookUpItems.LookUpItemsWeldType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LookupItemsWeldTypes");
                });

            modelBuilder.Entity("Quartz.Entities.Concrete.Project.Item.QuartzItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AttachmentIds")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DrawingSettingsId")
                        .HasColumnType("integer");

                    b.Property<int>("IsInspected")
                        .HasColumnType("integer");

                    b.Property<bool>("ShowLabel")
                        .HasColumnType("boolean");

                    b.Property<string>("TagNo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DrawingSettingsId");

                    b.ToTable("QuartzItems");
                });

            modelBuilder.Entity("Quartz.Entities.Concrete.Project.Item.QuartzItemFilter", b =>
                {
                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DrawingNo")
                        .HasColumnType("text");

                    b.Property<string>("FittingType")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("IsInspected")
                        .HasColumnType("integer");

                    b.Property<string>("PlantArea")
                        .HasColumnType("text");

                    b.Property<string>("PlantSystem")
                        .HasColumnType("text");

                    b.Property<string>("SerialNo")
                        .HasColumnType("text");

                    b.Property<string>("Specification")
                        .HasColumnType("text");

                    b.Property<string>("TagNo")
                        .HasColumnType("text");

                    b.Property<string>("WeldType")
                        .HasColumnType("text");

                    b.ToView("vw_SearchItem");
                });

            modelBuilder.Entity("Quartz.Entities.Concrete.Project.Item.QuartzItemsThicknessMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AttachmentIds")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<float>("MeasuredThickness")
                        .HasColumnType("real");

                    b.Property<float>("NominalThickness")
                        .HasColumnType("real");

                    b.Property<string>("PlantArea")
                        .HasColumnType("text");

                    b.Property<string>("PlantSystem")
                        .HasColumnType("text");

                    b.Property<int>("QuartzItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Specification")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuartzItemId");

                    b.ToTable("QuartzItemsThicknessMeasurements");
                });

            modelBuilder.Entity("Quartz.Entities.Concrete.Project.Item.QuartzItemsValveMaintenance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AttachmentIds")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Designation")
                        .HasColumnType("text");

                    b.Property<float>("IdealBarg")
                        .HasColumnType("real");

                    b.Property<string>("KKSNo")
                        .HasColumnType("text");

                    b.Property<float>("OpeningPressureBarg")
                        .HasColumnType("real");

                    b.Property<string>("PlantArea")
                        .HasColumnType("text");

                    b.Property<int>("QuartzItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("SerialNo")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("SupplierManufacturare")
                        .HasColumnType("text");

                    b.Property<DateTime>("TestDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Tested")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("QuartzItemId");

                    b.ToTable("QuartzItemsValveMaintenances");
                });

            modelBuilder.Entity("Quartz.Entities.Concrete.Project.Link.QuartzLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DrawingSettingsId")
                        .HasColumnType("integer");

                    b.Property<int>("MainDrawingSettingsId")
                        .HasColumnType("integer");

                    b.Property<bool>("ShowLabel")
                        .HasColumnType("boolean");

                    b.Property<string>("TagNo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MainDrawingSettingsId");

                    b.ToTable("QuartzLinks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "QUARTZ",
                            CreatedDate = new DateTime(2022, 11, 24, 11, 40, 23, 643, DateTimeKind.Local).AddTicks(6434),
                            DrawingSettingsId = 2,
                            MainDrawingSettingsId = 1,
                            ShowLabel = true,
                            TagNo = "Main"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "QUARTZ",
                            CreatedDate = new DateTime(2022, 11, 24, 11, 40, 23, 643, DateTimeKind.Local).AddTicks(6434),
                            DrawingSettingsId = 0,
                            MainDrawingSettingsId = 1,
                            ShowLabel = true,
                            TagNo = "Temp"
                        });
                });

            modelBuilder.Entity("Quartz.Entities.Concrete.Project.Link.QuartzLinksDrawingFeatures", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("DrawingSettingsId")
                        .HasColumnType("integer");

                    b.Property<string>("Features")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DrawingSettingsId")
                        .IsUnique();

                    b.ToTable("QuartzLinksDrawingFeatures");
                });

            modelBuilder.Entity("Quartz.Entities.Concrete.Project.Link.QuartzLinksDrawingSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AttachmentIds")
                        .HasColumnType("text");

                    b.Property<int>("CurrentDrawingId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DrawingNo")
                        .HasColumnType("text");

                    b.Property<string>("PlantArea")
                        .HasColumnType("text");

                    b.Property<string>("PlantSystem")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("QuartzLinksDrawingSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentDrawingId = 1,
                            DrawingNo = "General"
                        },
                        new
                        {
                            Id = 2,
                            CurrentDrawingId = 1,
                            DrawingNo = "Main",
                            PlantArea = "select",
                            PlantSystem = "select"
                        });
                });

            modelBuilder.Entity("Quartz.Entities.Concrete.Projects.Item.QuartzItemsInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<string>("ComponentType")
                        .HasColumnType("text");

                    b.Property<string>("FittingType")
                        .HasColumnType("text");

                    b.Property<float?>("OperatingPressureBar")
                        .HasColumnType("real");

                    b.Property<float?>("OperatingTempC")
                        .HasColumnType("real");

                    b.Property<float?>("PipeOdIn")
                        .HasColumnType("real");

                    b.Property<float?>("PipeThicknessMm")
                        .HasColumnType("real");

                    b.Property<int>("QuartzItemId")
                        .HasColumnType("integer");

                    b.Property<string>("SerialNo")
                        .HasColumnType("text");

                    b.Property<bool?>("ShowLabel")
                        .HasColumnType("boolean");

                    b.Property<string>("Specification")
                        .HasColumnType("text");

                    b.Property<string>("TagNo")
                        .HasColumnType("text");

                    b.Property<string>("WeldType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuartzItemId")
                        .IsUnique();

                    b.ToTable("QuartzItemsInformations");
                });

            modelBuilder.Entity("Quartz.Entities.Concrete.Projects.Item.QuartzItemsInspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AttachmentIds")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Method")
                        .HasColumnType("text");

                    b.Property<string>("Procedure")
                        .HasColumnType("text");

                    b.Property<int>("QuartzItemId")
                        .HasColumnType("integer");

                    b.Property<string>("ReportNo")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Technique")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuartzItemId");

                    b.ToTable("QuartzItemsInspections");
                });

            modelBuilder.Entity("Quartz.Entities.Concrete.Users.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "707b717a-d330-450f-a42c-9f2b7fcdfea1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "6eadcc3d-21a3-41b8-91bd-26988bb8d656",
                            Name = "Operator",
                            NormalizedName = "OPERATOR"
                        });
                });

            modelBuilder.Entity("Quartz.Entities.Concrete.Users.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fe13649b-6a19-4964-8db8-1332ba224904",
                            Email = "admin@quartz.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            FullName = "Admin Quartz",
                            LastName = "Quartz",
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@QUARTZ.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAECnTVUK/QxKYvnJiVDztpm9YuvXVCbwiW86jvTxkNOXv/27Nzr1OVjy4hbtRdcoZjg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a3635eb1-112c-4cca-9e6e-b81e636d99c2",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Quartz.Entities.Concrete.Users.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Quartz.Entities.Concrete.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Quartz.Entities.Concrete.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Quartz.Entities.Concrete.Users.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quartz.Entities.Concrete.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Quartz.Entities.Concrete.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Quartz.Entities.Concrete.Project.Item.QuartzItem", b =>
                {
                    b.HasOne("Quartz.Entities.Concrete.Project.Link.QuartzLinksDrawingSettings", "DrawingSettings")
                        .WithMany("QuartItems")
                        .HasForeignKey("DrawingSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DrawingSettings");
                });

            modelBuilder.Entity("Quartz.Entities.Concrete.Project.Item.QuartzItemsThicknessMeasurement", b =>
                {
                    b.HasOne("Quartz.Entities.Concrete.Project.Item.QuartzItem", "QuartzItem")
                        .WithMany("ThicknessMeasurements")
                        .HasForeignKey("QuartzItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuartzItem");
                });

            modelBuilder.Entity("Quartz.Entities.Concrete.Project.Item.QuartzItemsValveMaintenance", b =>
                {
                    b.HasOne("Quartz.Entities.Concrete.Project.Item.QuartzItem", "QuartzItem")
                        .WithMany("ValveMaintenances")
                        .HasForeignKey("QuartzItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuartzItem");
                });

            modelBuilder.Entity("Quartz.Entities.Concrete.Project.Link.QuartzLink", b =>
                {
                    b.HasOne("Quartz.Entities.Concrete.Project.Link.QuartzLinksDrawingSettings", "DrawingSettings")
                        .WithMany("QuartzLinks")
                        .HasForeignKey("MainDrawingSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DrawingSettings");
                });

            modelBuilder.Entity("Quartz.Entities.Concrete.Project.Link.QuartzLinksDrawingFeatures", b =>
                {
                    b.HasOne("Quartz.Entities.Concrete.Project.Link.QuartzLinksDrawingSettings", "DrawingSettings")
                        .WithOne("DrawingFeatures")
                        .HasForeignKey("Quartz.Entities.Concrete.Project.Link.QuartzLinksDrawingFeatures", "DrawingSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DrawingSettings");
                });

            modelBuilder.Entity("Quartz.Entities.Concrete.Projects.Item.QuartzItemsInformation", b =>
                {
                    b.HasOne("Quartz.Entities.Concrete.Project.Item.QuartzItem", "QuartzItem")
                        .WithOne("Information")
                        .HasForeignKey("Quartz.Entities.Concrete.Projects.Item.QuartzItemsInformation", "QuartzItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuartzItem");
                });

            modelBuilder.Entity("Quartz.Entities.Concrete.Projects.Item.QuartzItemsInspection", b =>
                {
                    b.HasOne("Quartz.Entities.Concrete.Project.Item.QuartzItem", "QuartzItem")
                        .WithMany("Inspections")
                        .HasForeignKey("QuartzItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuartzItem");
                });

            modelBuilder.Entity("Quartz.Entities.Concrete.Project.Item.QuartzItem", b =>
                {
                    b.Navigation("Information");

                    b.Navigation("Inspections");

                    b.Navigation("ThicknessMeasurements");

                    b.Navigation("ValveMaintenances");
                });

            modelBuilder.Entity("Quartz.Entities.Concrete.Project.Link.QuartzLinksDrawingSettings", b =>
                {
                    b.Navigation("DrawingFeatures");

                    b.Navigation("QuartItems");

                    b.Navigation("QuartzLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
